after exchange sources

diff --git a/home/sources/my_ex_paths b/home/sources/my_ex_paths
--- a/home/sources/my_ex_paths
+++ b/home/sources/my_ex_paths
@@ -1,4 +1,150 @@
 #!/bin/bash
+
+export TMP="$HOME/tmp"
+export TEMP="$TMP"
+export TMPDIR="$TMP"
+export TMPPREFIX="${TMPDIR}/zsh"
+
+if [ ! -d "${TMP}" ]; then mkdir "${TMP}"; fi
+# Use hostname in TMUX_TMPDIR as $HOME may be on nfs.
+export TMUX_TMPDIR="${TMPDIR}/tmux-${HOST}-${UID}"
+if [ ! -d "${TMUX_TMPDIR}" ]; then mkdir -p "${TMUX_TMPDIR}"; fi
+
+##########3
+
+if [ -f "$HOME/.keysdir/export" ]; then
+	export keysdir="$HOME/.keysdir"
+	source "$keysdir/export"
+else
+	echo "keys dir not found"
+fi
+
+# default apps
+export EDITOR="nvim"
+export TERMINAL="alacritty"
+# export BROWSER="firefox"
+
+# cleaning up home folder
+export XDG_CONFIG_HOME="$HOME/.config"
+export XDG_DATA_HOME="$HOME/.local/share"
+export XDG_STATE_HOME="$HOME/.local/state"
+export XDG_CACHE_HOME="$HOME/.cache"
+
+export GNUPGHOME="$XDG_DATA_HOME"/gnupg
+
+# export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
+# export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
+# export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
+
+export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
+
+###
+prependToPath "$HOME"/.local/bin
+# appendToPath "/usr/games"
+
+### Packagemanagers
+## Homebrew
+case "${OSTYPE}" in
+linux*) brew_path="/home/linuxbrew/.linuxbrew" ;;
+darwin*) brew_path="/opt/homebrew" ;;
+esac
+if [[ -f "${brew_path}/bin/brew" ]]; then
+	eval "$("${brew_path}"/bin/brew shellenv)"
+fi
+
+## GUIX
+appendToPath "$HOME"/.config/guix/current/bin
+appendToPath "$HOME"/.guix-profile/bin
+
+### Programming languages.
+## GO
+export GOROOT="/usr/local/go"
+export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
+export GOBIN="$GOPATH/bin"
+appendToPath "$GOROOT/bin"
+appendToPath "$GOBIN"
+
+## Python Environment Manager
+export CONDA_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}/miniconda3"
+export CONDARC="$HOME/.condarc"
+case "${OSTYPE}" in
+linux*) CONDA_PREFIX="$CONDA_ROOT" ;;
+darwin*) CONDA_PREFIX="" ;;
+esac
+if [[ -f ${CONDA_PREFIX}/bin/conda ]]; then
+	eval "$("${CONDA_PREFIX}/bin/conda" "shell.zsh" "hook")"
+fi
+
+## RUST
+export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
+export RUSTUP_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/rustup"
+prependToPath "$CARGO_HOME/bin"
+
+## Ruby Environment Manager
+export RBENV_ROOT=${XDG_DATA_HOME:-$HOME/.local/share}/rbenv
+# if programExists rbenv; then
+# 	eval "$(rbenv init - n)"
+# fi
+
+[ -f "/home/ru/.ghcup/env" ] && source "/home/ru/.ghcup/env" # ghcup-env
+
+## NODE Environment Managers
+# FastNodeManager in Rust "https://github.com/Schniz/fnm"
+# if programExists fnm; then
+# 	eval "$(fnm env --use-on-cd)"
+# fi
+
+# NodeVersionManage "https://github.com/nvm-sh/nvm"
+export NVM_DIR=${XDG_DATA_HOME:-$HOME/.local/share}/nvm
+# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
+
+export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
+export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
+
+GIT_HOME=$HOME/REPOS
+export GIT_HOME
+
+DOT_SHELL=$GIT_HOME/re_shell
+# BIN_SHELL=$DOT_SHELL/bin
+SHELLSOURCE=$DOT_SHELL/home/sources
+my_array=("aliases" "zsh_prompt")
+
+for m in "${my_array[@]}"; do
+	[[ -f "$SHELLSOURCE/my_$m" ]] && source "$SHELLSOURCE/my_$m"
+done
+
+# Test and then source exported variables.
+# my_array=("exports" "options" "aliases" "functions" "zle" "bindings" "compctl" "style" "misc" "paths" "prompt")
+#
+# for m in "${my_array[@]}"; do
+# 	[[ -f "$ZSHDDIR/zsh$m" ]] && source "$ZSHDDIR/zsh$m" || echo "Note: $ZSHDDIR/zsh$m in unavailable"
+# done
+
+my_repo=("inst" "shell" "run" "net")
+for r in "${my_repo[@]}"; do
+	[[ -d "$GIT_HOME/re_$r" ]] && eval DOT_"$r"="$GIT_HOME/re_$r" && export DOT_"$r"
+	if [ -d "$GIT_HOME/re_$r"/bin ]; then
+		eval BIN_"$r"="$GIT_HOME/re_$r/bin" && export BIN_"$r"
+		# for d in $(command du "\$BIN_$r" | cut -f2); do   # "\$BIN_$r" a not visible after eval?
+		for d in $(command find "$GIT_HOME/re_$r/bin" -maxdepth 1 -type d); do
+			appendToPath "$d"
+		done
+	fi
+done
+
+# Adds ~/.local/bin and subfolders to $PATH
+# export PATH="$PATH:${$(find ~/.local/bin -maxdepth 1 -type d -printf %p:)%%:}"
+
+# export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
+# export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
+# export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
+# export ZDOTDIR="$HOME/.config/zsh"
+
+export MANPAGER="less -R --use-color -Dd+r -Du+b"
+
+###############
+
 # Environment variables
 
 export ZSH_PLUGINS_ALIAS_TIPS_TEXT="Alias: "
@@ -13,6 +159,7 @@ export R_HOME=/usr/lib/R
 
 #export VIMRUNTIME=/usr/share/nvim/runtime
 
+export LC_ALL=ru_RU.UTF-8
 export LANG=ru_RU.UTF-8
 
 # export LD_LIBRARY_PATH=$HOME/miniconda3/envs/JupyterSystemEnv/lib:$LD_LIBRARY_PATH
